var allTechnologies = [
  'AIX',
  'AJAX',
  'ANT',
  'ASP.NET',
  'Access',
  'Accumulo',
  'Active Directory',
  'Amazon Web Services',
  'Android',
  'AngularJS',
  'Assembly',
  'Atlassian Tool Suite',
  'BASH',
  'BSD',
  'BackboneJS',
  'Bamboo',
  'Bootstrap',
  'C#',
  'C/C++',
  'CCNA',
  'CISSP',
  'CITRIX',
  'CSS/ CSS3',
  'Camel',
  'CentOS',
  'ClearCase',
  'ClearQuest',
  'Cloudbase',
  'Cloudera Hadoop Admin CCHA',
  'ColdFusion',
  'Collectd',
  'Confluence',
  'Coudera Hadoop Developer CCDH',
  'Crucible',
  'Crystal Reports',
  'DOJO',
  'DOORS Requirements Management Tool',
  'DWR',
  'Derby',
  'Distillery ',
  'Docker',
  'Dreamweaver',
  'EHCache',
  'EJB',
  'Eclipse',
  'Eclipse Plugins',
  'Elasticsearch',
  'Ethical Hacker ',
  'Excel',
  'Exchange',
  'ExtJS',
  'Fedora',
  'Fisheye',
  'Flex',
  'FrontPage',
  'Ganglia',
  'Giraph',
  'Git',
  'Google Web Toolkit',
  'Groovy',
  'Groovy on Grails',
  'GulpJS',
  'HDFS',
  'HP-UX)',
  'HTML/ HTML5',
  'Hadoop',
  'Hadoop',
  'Hibernate',
  'Hive',
  'IDA Pro',
  'ITIL V3',
  'Iterative',
  'Ivy',
  'J2EE',
  'JBoss',
  'JDBC',
  'JIRA',
  'JMS',
  'JMX',
  'JNDI',
  'JQuery',
  'JSF',
  'JSON',
  'JSP',
  'JUnit',
  'Java',
  'Javascript',
  'Jboss',
  'Jenkins/Hudson',
  'Jersey',
  'Jetty',
  'Kafka',
  'Kendo UI',
  'Linux (RedHat',
  'Logstash',
  'MSDOS',
  'MapReduce',
  'Maven',
  'Mercury TestDirector',
  'Mesos',
  'Microsoft Certified Professional (MCP) for NT Server',
  'Microsoft Certified Professional (MCP) for NT Server in the Enterprise',
  'Microsoft Certified Professional (MCP) for NT Workstation',
  'Microsoft Certified Systems Administrator (MCSA) ',
  'Mockito framework',
  'MongoDB',
  'MontaVista',
  'MySQL',
  'Nagios',
  'Netbeans',
  'Network +',
  'NoSQL',
  'OSGI',
  'Objectivity',
  'OpenShift',
  'OpenStack',
  'Oracle',
  'Oracle Certified Master ',
  'Orion',
  'PHP',
  'PKI',
  'PMP',
  'Perl',
  'Pig',
  'PostgreSQL',
  'PowerBuilder',
  'PowerPoint',
  'Project',
  'Puppet',
  'Putty',
  'Python',
  'RHEL',
  'Rally',
  'Rational Manual Tester',
  'Rational Suite Enterprise',
  'Rational TestManager',
  'ReactJS',
  'Redis',
  'Remedy',
  'RequisitePro',
  'Rose',
  'Ruby',
  'Ruby on Rails',
  'SCRUM',
  'SCRUM master ',
  'SPARQL',
  'SQL',
  'SQL',
  'Salt',
  'Scala',
  'Security +',
  'Selenium',
  'Sencha GXT',
  'Shell',
  'Slackware',
  'Snort',
  'SoapUI ',
  'Spark',
  'Splunk',
  'Spring',
  'Spring',
  'Stardog',
  'Storm',
  'Struts',
  'Studio',
  'Subversion',
  'Sun',
  'Swing',
  'Sybase',
  'Symbian OS',
  'TDD',
  'TRAC',
  'TestNG',
  'Tomcat',
  'Tomcat',
  'UML',
  'UNIX (Solaris',
  'Ubuntu',
  'UnderscoreJS',
  'VAX',
  'VB.NET',
  'VMS',
  'VMware',
  'Version One',
  'Visio',
  'WebSphere',
  'Weblogic',
  'WinRunner',
  'Windows',
  'Windows 9X/2000/XP/7',
  'Windows Mobile',
  'Windows NT',
  'Windows Vista',
  'Wireshark',
  'Word',
  'Works',
  'XML/XSLT',
  'XP',
  'Yellow Dog',
  'Zookeeper',
  'iOS'
]
var technologiesSection = document.querySelector('.technologies')
var input = document.querySelector('.technologies input')

input.focus()

input.addEventListener('input', function() {
  if (!input.value) {
    document.querySelector('.technologies .results').style.display = 'none'

    return
  }

  var matchedTechnologies = allTechnologies.filter(function(technology) {
    return technology.toLowerCase().indexOf(input.value.toLowerCase()) > -1
  })
  var newTechnologiesDiv = generateTechnologyEls(matchedTechnologies)

  technologiesSection.replaceChild(
    newTechnologiesDiv,
    technologiesSection.querySelector('.results')
  )

  newTechnologiesDiv.style.display = 'block'
})

function generateTechnologyEls(technologies) {
  var technologyDiv = createTechnologyDiv()

  technologies.forEach(function(technology) {
    var el = document.createElement('p')

    el.innerHTML = technology

    technologyDiv.appendChild(el)
  })

  return technologyDiv
}

function createTechnologyDiv() {
  var technologyDiv = document.createElement('div')

  technologyDiv.classList.add('results')

  return technologyDiv
}
